language: node_js

node_js:
  - "10"

script:
    - "npm test"
after_success:
    - 'npm install coveralls && npm install nyc && ./node_modules/.bin/nyc report --temp-directory=coverage --reporter=text-lcov | ./node_modules/.bin/coveralls'